# https://hrynko.github.io/blog/build-and-deploy-using-gh-actions/
name: Build and Deploy to Github Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read # for accessing the repository contents
  id-token: write # for verifying the deployment source
  pages: write # to be able deploy to GitHub Pages

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Where are we
        run: ls -la

      # steps for building the project
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: The stuff
        run: |
          cd web
          npm i
          npm run prod
          ls -la
          
      - name: Move to /web folder
        run: cd web      
      
      - name: Where are we
        run: ls -la
        
      - name: Install dependencies
        run: npm i
        
      - name: Build Production
        run: npm run prod
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: /web/dist
          
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      # steps for deploying the project to Github Pages
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        
    - name: Set up Pages
      uses: actions/configure-pages@v2
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: .
        
    - name: Deploy
      id: deployment # it was previously used to get the deployment URL
      uses: actions/deploy-pages@v1
